import Head from "next/head";
import BracketBoard from "../components/Bracket";
import Card from "../components/Card";
import { teams } from "../lib/types/bracket";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-red-500">
        <BracketBoard teams={teams} />
      </div>
    </div>
  );
}
